"""Initial migration.

Revision ID: 87050f7e6a27
Revises: 
Create Date: 2024-02-19 03:12:05.698493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87050f7e6a27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
